name: Automated Package Update

permissions:
  contents: write

on:
  schedule:
    - cron: '0 2 * * *' # 2:00 UTC = 4:00 Germany
  workflow_dispatch:
  push:
    branches:
      - update

jobs:
  update-deps:
    if: github.ref == 'refs/heads/recode'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout update branch
        uses: actions/checkout@v4
        with:
          ref: update
          fetch-depth: 0 # Needed for merging

      - name: Set up git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge recode into update
        run: |
          git fetch origin recode:recode
          git merge --no-ff recode || true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Update all dependencies
        run: pnpm update --latest

      - name: Check for changes
        id: check
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.check.outputs.changed == 'true'
        run: |
          git add .
          git commit -m "chore: automated update"
          git push origin update

      - name: Get date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update
          base: recode
          title: 'Automated Update ${{ steps.date.outputs.today }}'
          body: 'Automated dependency update via GitHub Actions.'
          delete-branch: false
